### ISSUE TITLE
Multiple layers

### ISSUE THREAD

**Issue by newluck77** [newluck77/fprsmap#5]
Have more than one layer, e.g.:

- one for T-Mobile Shops (where can I buy a FP?)
- one for repair shops (where can I get my FP repaired?)
- one for the [community Fairphone 2](https://forum.fairphone.com/t/current-location-of-the-community-fairphone-2/21519?u=stefan)location
- etc.

**Comment by Roboe** [comment]
Great idea! While I implement #8, can you look for a Leaftlet's function to clear markers? We'll probably need it.

**Comment by newluck77** [comment]
There actually is an ILayer object in Leaflet. I didn't dive into it, but I think we could just use [addLayer](http://leafletjs.com/reference.html#map-addlayer) and [removeLayer](http://leafletjs.com/reference.html#map-removelayer), where each layer contains a set of locations. (E.g. the set of locations we use now would go to one layer, which could be added and removed arbitrarily.)

**Comment by newluck77** [comment]
Check out the rather dirty implementation in the new [layers branch](https://github.com/newluck77/fprsmap/tree/layers?files=1). I did it following this [tutorial](http://leafletjs.com/examples/layers-control.html). The result needs some clean up, but the setup is straightforward.

**Comment by Roboe** [comment]
Woa, that was rather straightforward, indeed. I'm finishing #8 right now, we can take this issue after that

**Comment by Roboe** [comment]
We can make a [polyline](http://leafletjs.com/reference.html#polyline) for the community FP2, :)

**Comment by newluck77** [comment]
> We can make a polyline for the community FP2, :)

That would have to be maintained manually, wouldn't it?

**Comment by Roboe** [comment]
If Fairphone provides us with an endpoint with a history of locations… it wouldn't. I guess they have some kind of tracking over the FP2 location?

First implementation (until we get the FP official backend) would be manual, yes, but we have done that before with communities, didn't we? We have the FP2 journal thread in the forum, we just need to pick the cities and make a YAML/JSON

**Comment by newluck77** [comment]
> I guess they have some kind of tracking over the FP2 location?

I don't think so. They have the scratch map: https://forum.fairphone.com/t/current-location-of-the-community-fairphone-2/21519/3?u=stefan ;)
