### ISSUE TITLE
Have URL suffix per layer

### ISSUE THREAD

**Issue by newluck77** [newluck77/fprsmap#6]
For each layer specify a URL suffix that can be used to have layers ( #5 ) open by default. Something along the lines of `https://newluck77.github.io/fprsmap/?l=tmobile` or `https://newluck77.github.io/fprsmap/?l=tmobile&l=repair`.

**Comment by Roboe** [comment]
Multiple layer selection will look more like `https://newluck77.github.io/fprsmap/?l=tmobile,repair`. Keys (`l` in this case) should not be duplicated.

**Comment by newluck77** [comment]
The problem I'm facing is that I cannot use the location object's property and pass it to the initMap(defaultlayer) function as an object identifier.

**Comment by newluck77** [comment]
@Roboe Try it out (add for example `?l=shops` to the URL)! Works great! :D 

PS.: Downside is, that also `?shopsmeetupsangels` would work... ;)
